# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#

font_family CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14

# Tab managment with vim-like keys
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab
map ctrl+shift+alt+h move_tab_backward
map ctrl+shift+alt+l move_tab_forward
